name = "koralabs/handles-personalization"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "MIT"
description = "Aiken contracts for handles-personalization"

[repository]
user = "koralabs"
project = "handles-personalization"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "2.1.0"
source = "github"

[config]
